---
title: "Exploring Patient Table"
output: rmarkdown::github_document
---
Author: [Mahdi Moqri](https://www.moqri.com/)

The patinet table is a core part of the eICU-CRD and contains all information related to tracking patient unit stays. The table also contains patient demographics and hospital level information.


### Loading libraries
```{r message=FALSE}
library(data.table)
library(dplyr)
library(magrittr)
#library(plyr)
library(knitr)
library(ggplot2)
library(visreg)
library(rpart)
library("caret")
library(rpart.plot)
library(corrplot)
```

```{r}
# data_folder is the local path to your data
dfPatient=fread('data/patient.csv')
dfApache=fread('data/apachePatientResult.csv')
df= merge(x = dfPatient, y = dfApache, by = "patientunitstayid", all = TRUE)
```
### Age
```{r message=FALSE, warning=FALSE}
df %<>% mutate(age_impute= (ifelse(age=='> 89',90, as.numeric(age))))
age=df[!is.na(df$age_impute),]$age_impute
```

###Apachi Score
```{r}

NewData=df%>%select(c(age_impute,ethnicity,apachescore))%>%subset(ethnicity %in% c("Caucasian","African American"))%>%subset(apachescore!='')%>%group_by(ethnicity, age_impute) %>% summarise(meanApachi=mean(apachescore))
NewData<-na.omit(NewData)
ggplot(NewData, aes(x=age_impute, y=meanApachi)) +
 geom_point(aes(color=ethnicity))


########5years
b <- c(15,20,25,30,35,40,45,50,55,60,65,70,75,80,85,90)
names=c("15-20","20-25","25-30","30-35","35-40","40-45","45-50","50-55","55-60","60-65","65-70","70-75","75-80","80-85","85-90")
# b <- c(10,20,30,40,50,60,70,80,90)
# names=c("10-20","20-30","30-40","40-50","50-60","60-70","70-80","80-90")
NewData$BreakedAge=cut(NewData$age_impute, breaks = b, labels = names)
NewData<-na.omit(NewData)



ggplot(NewData,aes(x=BreakedAge, y=meanApachi,width=.45,fill=factor(ethnicity)))+
  geom_bar(stat="identity",position="dodge")+
  
  guides(fill=guide_legend(title="Ethnicity")) +
  xlab("Age")+ylab("APACHE score") +
    theme(axis.text.x = element_text(angle = 90, hjust = 1, size=10,color="black"))






```
####correlation of Apachi and Morality
```{r}
ApachiOutPut=df%>%select(c(apachescore,unitdischargestatus))%>%subset(apachescore!='')%>%subset (unitdischargestatus %in% c("Alive","Expired"))
ApachiOutPut$unitdischargestatus=as.factor(ApachiOutPut$unitdischargestatus)
correlation <- cor(ApachiOutPut$apachescore,as.numeric(ApachiOutPut$unitdischargestatus))
correlation

ggplot(ApachiOutPut, aes( x=unitdischargestatus, y=apachescore)) + 
  geom_violin(trim=FALSE)+ geom_boxplot(width=0.1)+xlab("Unit discharge status")+ylab("APACHE score") 

```


#most important disease
```{r}
DiseaseTable=df %>%subset(apacheadmissiondx %in% c("Cardiac arrest (with or without respiratory arrest; for respiratory arrest see Respiratory System)","CHF, congestive heart failure","CVA, cerebrovascular accident/stroke","Sepsis, pulmonary","Sepsis, renal/UTI (including bladder)"))%>% group_by(apacheadmissiondx) %>%
  summarise(expired=sum(hospitaldischargestatus=="Expired"),total=sum(hospitaldischargestatus %in%c("Expired","Alive")),percentage=expired/total*100) 
DiseaseTable<-na.omit(DiseaseTable)
DiseaseTable<-filter (DiseaseTable, total>4500)
DiseaseTable<-filter (DiseaseTable, percentage>10)
DiseaseTable$diseaseId=as.numeric(as.factor(DiseaseTable$apacheadmissiondx))
```
#Box plot
```{r, fig.height=8,fig.width=8}
BoxPlot=df%>%subset(unitdischargestatus %in%c("Expired","Alive"))%>%subset(apacheadmissiondx %in% DiseaseTable$apacheadmissiondx)%>%subset(apachescore!="")
BoxPlot$apacheadmissiondx[which(BoxPlot$apacheadmissiondx=="Cardiac arrest (with or without respiratory arrest; for respiratory arrest see Respiratory System)")]<-"Cardiac arrest"
# ati=BoxPlot%>%select (c("apacheadmissiondx","unitdischargestatus","apachescore"))%>%group_by(apacheadmissiondx,unitdischargestatus)%>%summarise(med=median(apachescore))
ggplot(BoxPlot, aes(x=apacheadmissiondx, y=apachescore, fill=unitdischargestatus)) +
    geom_boxplot()+theme(axis.text.x = element_text(angle = 45, hjust = 1, size=10,color="black"))+xlab("Admission diagnosis")+ylab("APACHE score")+guides(fill=guide_legend(title="Unit discharge status"))
```	


```{r}
CHFPatients=df%>%subset(unitdischargestatus %in%c("Expired","Alive"))%>%subset(apacheadmissiondx=="CHF, congestive heart failure")%>%subset(apachescore!="")
```

```{r}
NewData=CHFPatients%>%select(c("unitdischargestatus","apachescore","age"))
NewData$unitdischargestatus=as.factor(NewData$unitdischargestatus)
mylogit <- glm(unitdischargestatus~., data = NewData, family = "binomial")
#print(mylogit)
summary(mylogit)
```

```{r}
df= left_join(x = df, y = dfapacheApsVar, by = "patientunitstayid")
df= left_join(x = df, y = dfapachePredVar, by = "patientunitstayid")
ApachiException=df%>%select(c())%>%subset(apachescore>100&hospitaldischargestatus=="Alive" |apachescore<50 &hospitaldischargestatus=="Expired")
ApachiException=na.omit(ApachiException)
ApachiException$hospitaldischargestatus <- factor(ApachiException$hospitaldischargestatus)
mylogit <- glm(hospitaldischargestatus~., data = ApachiException, family = "binomial")
print(mylogit)
summary(mylogit)
```

